# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action
name: Build .NET package
description: Build a .NET package to be published to nuget.org

inputs:
  project:
    description: The project's name (also the folder name)
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore dependencies
      shell: bash
      run: dotnet restore ${{ inputs.project }}/${{ inputs.project }}.csproj --no-dependencies

    - name: Build ${{ inputs.project }}
      shell: bash
      run: dotnet build ${{ inputs.project }}/${{ inputs.project }}.csproj -c Release --no-restore

    - name: Pack ${{ inputs.project }} to local feed
      shell: bash
      run: dotnet pack ${{ inputs.project }}/${{ inputs.project }}.csproj -c Release -o ~/localfeed
