name: .NET NuGet package release
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Add local NuGet feed
      run: |
        mkdir -p ~/localfeed
        dotnet nuget add source ~/localfeed --name LocalFeed

    - name: Build DeviceProgramming
      uses: ./.github/template/build-package
      with:
        project: DeviceProgramming

    - name: Build LibUsbDfu
      uses: ./.github/template/build-package
      with:
        project: LibUsbDfu

    - name: Push packages to NuGet.org
      run: dotnet nuget push ~/localfeed/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

    - name: Push packages to GitHub Packages
      run: |
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/IntergatedCircuits/index.json"
        dotnet nuget push ~/localfeed/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${GITHUB_REF_NAME}" \
          --title "${GITHUB_REF_NAME#v}" \
          --verify-tag \
          --generate-notes
